coverage:
  ignore:
    - apps/**
    - packages/playwright/**
    - commitlint.config.ts
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
          - packages/
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
          - packages/
