coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
          - packages/
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
          - packages/