//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Executor
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const executorAbi = [
	{ type: "error", inputs: [], name: "AlreadyAcknowledged" },
	{ type: "error", inputs: [], name: "AlreadyMapped" },
	{ type: "error", inputs: [], name: "ExceedsMaxAssets" },
	{ type: "error", inputs: [], name: "FailedTransfer" },
	{ type: "error", inputs: [], name: "IncorrectFeeAmount" },
	{ type: "error", inputs: [], name: "NotActiveValidator" },
	{
		type: "error",
		inputs: [
			{ name: "btcBalance", internalType: "uint256", type: "uint256" },
			{ name: "btcFee", internalType: "uint256", type: "uint256" },
		],
		name: "NotEnoughBalance",
	},
	{
		type: "error",
		inputs: [
			{ name: "requiredFees", internalType: "uint256", type: "uint256" },
			{ name: "btcAmount", internalType: "uint256", type: "uint256" },
		],
		name: "NotEnoughFees",
	},
	{
		type: "error",
		inputs: [
			{ name: "requiredFees", internalType: "uint256", type: "uint256" },
			{ name: "btcAmount", internalType: "uint256", type: "uint256" },
		],
		name: "NotEnoughRunesFees",
	},
	{ type: "error", inputs: [], name: "NotNextEpochValidator" },
	{ type: "error", inputs: [], name: "NotValRegistryCalling" },
	{ type: "error", inputs: [], name: "ReentrancyGuardReentrantCall" },
	{ type: "error", inputs: [], name: "RuneZeroAddress" },
	{
		type: "error",
		inputs: [{ name: "token", internalType: "address", type: "address" }],
		name: "SafeERC20FailedOperation",
	},
	{ type: "error", inputs: [], name: "WrongLength" },
	{
		type: "error",
		inputs: [{ name: "asset", internalType: "address", type: "address" }],
		name: "ZeroRunesBalance",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "txHash",
				internalType: "bytes32",
				type: "bytes32",
				indexed: true,
			},
			{ name: "from", internalType: "address", type: "address", indexed: true },
			{
				name: "btcAmount",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "Acknowledged",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "nMidlAddress",
				internalType: "contract IERC20Extended",
				type: "address",
				indexed: false,
			},
			{
				name: "btcAddress",
				internalType: "bytes32",
				type: "bytes32",
				indexed: false,
			},
		],
		name: "AddedAsset",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "receiver",
				internalType: "bytes32",
				type: "bytes32",
				indexed: false,
			},
			{
				name: "receiverBTC",
				internalType: "bytes32",
				type: "bytes32",
				indexed: false,
			},
			{
				name: "btcAmountToSend",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "btcAmountToBurn",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "assets",
				internalType: "bytes32[]",
				type: "bytes32[]",
				indexed: false,
			},
			{
				name: "amounts",
				internalType: "uint256[]",
				type: "uint256[]",
				indexed: false,
			},
		],
		name: "Completed",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "midlERC20",
				internalType: "contract IERC20Extended",
				type: "address",
				indexed: false,
			},
			{
				name: "runeId",
				internalType: "bytes32",
				type: "bytes32",
				indexed: false,
			},
			{
				name: "decimals",
				internalType: "uint8",
				type: "uint8",
				indexed: false,
			},
		],
		name: "SynthRuneMappingRequested",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "validator",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "nMidlAddress",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "btcAddress",
				internalType: "bytes32",
				type: "bytes32",
				indexed: false,
			},
			{
				name: "assetType",
				internalType: "enum Executor.AssetType",
				type: "uint8",
				indexed: false,
			},
		],
		name: "VotedAddAsset",
	},
	{
		type: "function",
		inputs: [],
		name: "BTC_EDICT_BYTES",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "BTC_TX_INPUT_VBYTES",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "BTC_TX_KEYGEN_BYTES",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "BTC_TX_MAX_OUTPUT_VBYTES",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "BTC_TX_MIN_OUTGOING_BYTES",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "COMPLETE_TX_COST",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "GAS_PRICE",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "GLOBAL_PARAMS_ADDRESS",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "MAX_ASSETS",
		outputs: [{ name: "", internalType: "uint8", type: "uint8" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "PERCENT_SCALE",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "RUNES_MAGIC_VALUE",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "RUNE_MAPPING_FEE",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "SCALE_BTC",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "SYNTH_RESERVOIR",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "TREASURY_ADDRESS",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "VALIDATORS_REGISTRY",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{
				name: "_txData",
				internalType: "struct Executor.AcknowledgeTxData",
				type: "tuple",
				components: [
					{ name: "txHash", internalType: "bytes32", type: "bytes32" },
					{ name: "from", internalType: "address", type: "address" },
					{ name: "btcAmount", internalType: "uint256", type: "uint256" },
					{ name: "assets", internalType: "bytes32[]", type: "bytes32[]" },
					{ name: "amounts", internalType: "uint256[]", type: "uint256[]" },
					{ name: "metadata", internalType: "bytes32[]", type: "bytes32[]" },
					{ name: "synthAssets", internalType: "address[]", type: "address[]" },
					{ name: "btcTx", internalType: "bytes", type: "bytes" },
				],
			},
		],
		name: "acknowledgeTx",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_nMidlAddress", internalType: "address", type: "address" },
			{ name: "_btcAddress", internalType: "bytes32", type: "bytes32" },
			{
				name: "_assetType",
				internalType: "enum Executor.AssetType",
				type: "uint8",
			},
		],
		name: "addAsset",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "", internalType: "address", type: "address" },
			{ name: "", internalType: "bytes32", type: "bytes32" },
		],
		name: "assetQuorumId",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "btcNMidlAddresses",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "btcNMidlSynthAddresses",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_receiver", internalType: "bytes32", type: "bytes32" },
			{ name: "_receiverBTC", internalType: "bytes32", type: "bytes32" },
			{ name: "_assets", internalType: "address[]", type: "address[]" },
			{ name: "_amounts", internalType: "uint256[]", type: "uint256[]" },
		],
		name: "completeTx",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "payable",
	},
	{
		type: "function",
		inputs: [{ name: "_runeId", internalType: "bytes32", type: "bytes32" }],
		name: "getAssetAddressByRuneId",
		outputs: [
			{ name: "assetAddress", internalType: "address", type: "address" },
			{
				name: "assetType",
				internalType: "enum Executor.AssetType",
				type: "uint8",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_assetAddress", internalType: "address", type: "address" },
		],
		name: "getRuneIdByAssetAddress",
		outputs: [
			{ name: "runesId", internalType: "bytes32", type: "bytes32" },
			{
				name: "assetType",
				internalType: "enum Executor.AssetType",
				type: "uint8",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "address", type: "address" }],
		name: "nMidlBtcAddresses",
		outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "address", type: "address" }],
		name: "nMidlBtcSynthAddresses",
		outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "quorumExecuted",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{
				name: "_midlERC20",
				internalType: "contract IERC20Extended",
				type: "address",
			},
			{ name: "_runeId", internalType: "bytes32", type: "bytes32" },
		],
		name: "requestAddAsset",
		outputs: [],
		stateMutability: "payable",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "txsOrigins",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "valueQuorum",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "", internalType: "bytes32", type: "bytes32" },
			{ name: "", internalType: "address", type: "address" },
		],
		name: "valueQuorumVoted",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// GlobalParams
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const globalParamsAbi = [
	{ type: "error", inputs: [], name: "AlreadyPrefinalizing" },
	{ type: "error", inputs: [], name: "AlreadyProvidedFeeRate" },
	{ type: "error", inputs: [], name: "AlreadySetInitialTSS" },
	{ type: "error", inputs: [], name: "GracePeriodNotElapsed" },
	{ type: "error", inputs: [], name: "InvalidParams" },
	{ type: "error", inputs: [], name: "NoActiveFeeRateUpdate" },
	{ type: "error", inputs: [], name: "NotActiveValidator" },
	{ type: "error", inputs: [], name: "NotInPrefinalizingState" },
	{ type: "error", inputs: [], name: "NotNextEpochValidator" },
	{ type: "error", inputs: [], name: "NotValRegistryCalling" },
	{ type: "error", inputs: [], name: "QuorumNotReached" },
	{ type: "error", inputs: [], name: "ReentrancyGuardReentrantCall" },
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "contractAddr",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "methodSig",
				internalType: "bytes4",
				type: "bytes4",
				indexed: false,
			},
		],
		name: "Allowed",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "contractAddr",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "methodSig",
				internalType: "bytes4",
				type: "bytes4",
				indexed: false,
			},
		],
		name: "Disallowed",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "providersCount",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "FeeRatePrefinalized",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "validator",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "feeRate",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "FeeRateProvided",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "initialTSS",
				internalType: "bytes32",
				type: "bytes32",
				indexed: false,
			},
		],
		name: "InitialTSSSet",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "newTSS",
				internalType: "bytes32",
				type: "bytes32",
				indexed: false,
			},
		],
		name: "NextEpochTSSSet",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "quorumID",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "threshold",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "SetBTCThreshold",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "quorumID",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "threshold",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "SetMidlThreshold",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "epoch",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "validator",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{ name: "tx", internalType: "bytes", type: "bytes", indexed: false },
		],
		name: "SetTSSMigrationTransaction",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "lastFeeUpdatedIndex",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "feeRate",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "UpdatedBTCFeeRate",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "validator",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "contractAddress",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "methodSig",
				internalType: "bytes4",
				type: "bytes4",
				indexed: false,
			},
		],
		name: "VotedAllowMethod",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "validator",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "contractAddress",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "methodSig",
				internalType: "bytes4",
				type: "bytes4",
				indexed: false,
			},
		],
		name: "VotedDisallowMethod",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "validator",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "voteID",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "threshold",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "VotedSetBTCThreshold",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "validator",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "voteID",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "threshold",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "VotedSetMidlThreshold",
	},
	{
		type: "function",
		inputs: [],
		name: "FEE_RATE_MARKUP_PERCENT",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "GRACE_PERIOD",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "INTERNAL_FEE_RATE_MARKUP_PERCENT",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "PERCENT_SCALE",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "VALIDATORS_REGISTRY",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_sender", internalType: "address", type: "address" },
			{ name: "_contractAddr", internalType: "address", type: "address" },
			{ name: "_methodSig", internalType: "bytes4", type: "bytes4" },
		],
		name: "allowMethod",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "", internalType: "address", type: "address" },
			{ name: "", internalType: "address", type: "address" },
			{ name: "", internalType: "bytes4", type: "bytes4" },
		],
		name: "allowedNonBTCTxs",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "btcFeeRate",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "btcThreshold",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "btcThresholdQuorumID",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_sender", internalType: "address", type: "address" },
			{ name: "_contractAddr", internalType: "address", type: "address" },
			{ name: "_methodSig", internalType: "bytes4", type: "bytes4" },
		],
		name: "disallowMethod",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		name: "feeRateProvidersCount",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "feeRateUpdateActive",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "finalizeFeeRate",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "getTSSAddress",
		outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "internalBTCFeeRate",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "lastFeeUpdate",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "", internalType: "address", type: "address" },
			{ name: "", internalType: "address", type: "address" },
			{ name: "", internalType: "bytes4", type: "bytes4" },
		],
		name: "methodQuorumId",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "midlThreshold",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "midlThresholdQuorumID",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "prefinalizeFeeRate",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "prefinalizeTimestamp",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "_feeRate", internalType: "uint256", type: "uint256" }],
		name: "provideFeeRate",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "", internalType: "uint256", type: "uint256" },
			{ name: "", internalType: "address", type: "address" },
		],
		name: "providedFeeRate",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "quorumExecuted",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "_initialTSS", internalType: "bytes32", type: "bytes32" }],
		name: "setInitialTSS",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_btcThreshold", internalType: "uint256", type: "uint256" },
		],
		name: "setMinBTCThreshold",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_midlThreshold", internalType: "uint256", type: "uint256" },
		],
		name: "setMinMidlThreshold",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_newTSS", internalType: "bytes32", type: "bytes32" },
			{ name: "_epoch", internalType: "uint256", type: "uint256" },
		],
		name: "setNextEpochTSS",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "_tx", internalType: "bytes", type: "bytes" }],
		name: "setTSSMigrationTransaction",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		name: "tssByEpoch",
		outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		name: "tssMigrationTx",
		outputs: [{ name: "", internalType: "bytes", type: "bytes" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "", internalType: "uint256", type: "uint256" },
			{ name: "", internalType: "address", type: "address" },
		],
		name: "validatorFeeRates",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "valueQuorum",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "", internalType: "bytes32", type: "bytes32" },
			{ name: "", internalType: "address", type: "address" },
		],
		name: "valueQuorumVoted",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
] as const;
