import { generateIdentIcon } from "@appbak3r/sushi-identicon";
import { css, cx } from "styled-system/css";
import { type Token, token } from "styled-system/tokens";

type IdentIconProps = {
	hash: string;
	size?: number | string;
	className?: string;
};

export const IdentIcon = ({ hash, size = 6, className }: IdentIconProps) => {
	const iconSvg = generateIdentIcon(hash, true);

	return (
		<span
			// biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by a trusted library
			dangerouslySetInnerHTML={{ __html: iconSvg }}
			className={cx(
				css({
					display: "inline-block",
					borderRadius: "full",
					overflow: "hidden",
				}),
				className,
			)}
			style={{
				width: token.var(`sizes.${size}` as Token) ?? size,
				height: token.var(`sizes.${size}` as Token) ?? size,
			}}
		/>
	);
};
